services:
  db:
    image: postgres:18
    container_name: postgres-dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dbadminadmin
      POSTGRES_DB: lavacar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: